package jopt.csp.spi.arcalgorithm.domain;

import jopt.csp.variable.PropagationFailureException;
/**
 * Interface to implement in order to receive events generated by a domain
 */
public interface DomainChangeListener {
    /**
     * Method invoked by domain when a domain change event is fired
     */
    public void domainChange(DomainChangeEvent ev) throws PropagationFailureException;
    
    /**
     * Method invoked by domain when a choice point pop occurs
     */
    public void choicePointPop();
    
    /**
     * Method invoked by domain when a choice point push occurs
     */
    public void choicePointPush();
}