package jopt.csp.spi.arcalgorithm.graph.node;

/**
 * Interface to implement in order to receive events generated by a node
 */
public interface NodeChangeListener {
    /**
     * Method invoked by node when a node change event is fired
     */
    public void nodeChange(NodeChangeEvent ev);
}